name: online_groceries_store_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  #Internationalization
  intl: ^0.20.2

  #Network
  dio: ^5.7.0
  retrofit: ^4.4.1

  #UI
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0

  #Architecture
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^8.0.1
  injectable: ^2.5.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  #Logger
  pretty_dio_logger: ^1.4.0
  logger: ^2.5.0

  #Storage
  shared_preferences: ^2.3.3

  #Security
  flutter_secure_storage: ^9.2.3

  #Util
  dartz: ^0.10.1
  cupertino_icons: ^1.0.8

  #Routing
  go_router: ^15.0.0

  #Deeplink
  chottu_link: ^1.0.19

  #Share
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.14

  injectable_generator: ^2.7.0

  retrofit_generator: ^9.1.7

  json_serializable: ^6.9.3

  freezed: ^2.5.8

  flutter_gen_runner: ^5.11.0

flutter_gen:
  output: lib/core/assets_gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/


  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular-w400.otf
          weight: 400
        - asset: assets/fonts/Gilroy-SemiBold-w600.otf
          weight: 600
